apiVersion: v1
kind: Service
metadata:
  name: degreecalculator
spec:
  type: NodePort
  selector:
    app: degreecalculator
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001
