apiVersion: v1
kind: Service
metadata:
  name: degreecalculatorapi
spec:
  type: NodePort
  selector:
    app: degreecalculatorapi
  ports:
  - protocol: TCP
    port: 3332
    targetPort: 3332
    nodePort: 30002
